version: '3.9'
services:
  nginx:
    image: nginx:stable-alpine
    networks:
      - pkt-network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

  node-app:
    build: .
    image: mar436/phitauportal
    networks:
      - pkt-network
    env_file:
      - ./.env

networks:
  pkt-network:
    driver: bridge