version: '3.9'
services:
  nginx:
    image: nginx:stable-alpine
    networks:
      - phitau-portal
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  node-app:
    build: .
    image: mar436/phitauportal
    networks:
      - phitau-portal
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env

networks:
  phitau-portal:
    driver: bridge